# Generated by Django 5.2.15 on 2026-06-20 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('quantity_required', models.PositiveIntegerField()),
                ('quantity_have', models.PositiveIntegerField()),
                ('quantity_needed', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='inventory.dailyreport')),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
    ]
