# Generated by Django 5.2.15 on 2026-07-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_dailyreportsnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_name',
            field=models.CharField(choices=[('Gloves Set', 'Gloves Set'), ('Hose Head', 'Hose Head'), ('Knee Pad Set', 'Knee Pad Set'), ('Pro Grip', 'Pro Grip'), ('Orange Soap', 'Orange Soap'), ('Mini Roller', 'Mini Roller'), ('Paver', 'Paver'), ('Mini Brushes', 'Mini Brushes'), ('Scrapers', 'Scrapers'), ('Flat Head', 'Flat Head'), ('Scissors', 'Scissors'), ('Bottle', 'Bottle'), ('Brushes', 'Brushes'), ('Buckets', 'Buckets'), ('Sealing Buckets', 'Sealing Buckets'), ('Rocks', 'Rocks'), ('Masks', 'Masks'), ('Guns', 'Guns'), ('Battery', 'Battery'), ('Safety Glasses', 'Safety Glasses'), ('New Brushes', 'New Brushes'), ('Clear Seal Bucket', 'Clear Seal Bucket'), ('Garbage Bags', 'Garbage Bags'), ('Heads for Roller', 'Heads for Roller'), ('Head for Mini Roller', 'Head for Mini Roller'), ('Respirator', 'Respirator'), ('Pebbles', 'Pebbles'), ('Crack Fill', 'Crack Fill')], max_length=100),
        ),
    ]
